lyceum/about/urls.py
from django.urls import path

from about import views

app_name = "about"
urlpatterns = [
    path("", views.DescriptionView.as_view(), name="description"),
]

lyceum/catalog/urls.py
from django.urls import path
from django.urls import re_path
from django.urls import register_converter

from catalog import converters
from catalog import views

register_converter(converters.MyIntegerConverter, "integer")

app_name = "catalog"
urlpatterns = [
    path(
        "",
        views.ItemListView.as_view(),
        name="item_list",
    ),
    path(
        "new/",
        views.NewItemListView.as_view(),
        name="new_item_list",
    ),
    path(
        "friday/",
        views.FridayItemListView.as_view(),
        name="friday_item_list",
    ),
    path(
        "unchecked/",
        views.UncheckedItemListView.as_view(),
        name="unchecked_item_list",
    ),
    path(
        "<int:id>/",
        views.ItemDetailView.as_view(),
        name="item_detail",
    ),
    re_path(
        r"re/(?P<id>[1-9][0-9]*)/",
        views.ItemDetailView.as_view(),
        name="detail_re",
    ),
    path(
        r"converter/<integer:id>/",
        views.ItemDetailView.as_view(),
        name="detail_converter",
    ),
]

lyceum/lyceum/urls.py
from django.conf import settings
from django.conf.urls.static import static
import django.contrib.admin
import django.contrib.auth.urls
import django.urls

import about.urls
import catalog.urls
import download.urls
import feedback.urls
import homepage.urls
import statistic.urls
import users.urls

urlpatterns = [
    django.urls.path("", django.urls.include(homepage.urls)),
    django.urls.path("about/", django.urls.include(about.urls)),
    django.urls.path("feedback/", django.urls.include(feedback.urls)),
    django.urls.path("catalog/", django.urls.include(catalog.urls)),
    django.urls.path("download/", django.urls.include(download.urls)),
    django.urls.path("statistic/", django.urls.include(statistic.urls)),
    django.urls.path("admin/", django.contrib.admin.site.urls),
    django.urls.path("auth/", django.urls.include(users.urls)),
    django.urls.path("auth/", django.urls.include(django.contrib.auth.urls)),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar

    urlpatterns.append(
        django.urls.path("__debug__/", django.urls.include(debug_toolbar.urls))
    )

lyceum/users/urls.py
from django.contrib.auth.decorators import login_required
import django.contrib.auth.views
import django.urls

import users.views

app_name = "users"
urlpatterns = [
    django.urls.path(
        "register/",
        users.views.Register.as_view(),
        name="register",
    ),
    django.urls.path(
        "activate/<str:name>/",
        users.views.ActivateUsers.as_view(),
        name="activate",
    ),
    django.urls.path(
        "recovery/<str:name>/",
        users.views.UserRecovery.as_view(),
        name="recovery",
    ),
    django.urls.path(
        "user_list/",
        users.views.UsersList.as_view(),
        name="users_list",
    ),
    django.urls.path(
        "user_detail/<int:id>/",
        users.views.UsersDetail.as_view(),
        name="user_detail",
    ),
    django.urls.path(
        "profile/",
        login_required(users.views.UsersProfile.as_view()),
        name="profile",
    ),
    django.urls.path(
        "login/",
        django.contrib.auth.views.LoginView.as_view(
            template_name="users/login.html",
        ),
        name="login",
    ),
    django.urls.path(
        "logout/",
        django.contrib.auth.views.LogoutView.as_view(
            template_name="users/logout.html",
        ),
        name="logout",
    ),
    django.urls.path(
        "password_change/",
        django.contrib.auth.views.PasswordChangeView.as_view(
            template_name="users/password_change_form.html",
        ),
        name="password_change",
    ),
    django.urls.path(
        "password_change/done/",
        django.contrib.auth.views.PasswordChangeDoneView.as_view(
            template_name="users/password_change_done.html",
        ),
        name="password_change_done",
    ),
    django.urls.path(
        "password_reset/",
        django.contrib.auth.views.PasswordResetView.as_view(
            template_name="users/password_reset.html",
        ),
        name="password_reset",
    ),
    django.urls.path(
        "password_reset/done/",
        django.contrib.auth.views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html",
        ),
        name="password_reset_done",
    ),
    django.urls.path(
        "reset/<uidb64>/<token>/",
        django.contrib.auth.views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
        ),
        name="password_reset_confirm",
    ),
    django.urls.path(
        "reset/done/",
        django.contrib.auth.views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html",
        ),
        name="password_reset_complete",
    ),
]

lyceum/templates/include/footer.html
{% load static %}
{% load i18n %}

<footer class="footer-area section-padding">
  <div class="container">
    <div class="row">
      <div class="col-lg-3  col-md-6 col-sm-6">
        <div class="single-footer-widget">
          <h6>{% translate 'About as' %}</h6>
          <p>{% translate 'We take care of animals and help them find the best owners. Only the cutest cats for the most caring hands.' %} </p>
        </div>
      </div>
      <div class="col-lg-3  col-md-6 col-sm-6">

      </div>
      <div class="col-lg-3  col-md-6 col-sm-6">
        <div class="single-footer-widget mail-chimp">
          <h6 class="mb-20">{% translate 'Cute animals' %}</h6>
          <ul class="instafeed d-flex flex-wrap">
            <li><img class="img-fluid" src=" {% static 'img/plug.jpg'%} " alt=""></li>
            <li><img class="img-fluid" src=" {% static 'img/plug.jpg'%} " alt=""></li>
            <li><img class="img-fluid" src=" {% static 'img/plug.jpg'%} " alt=""></li>
            <li><img class="img-fluid" src=" {% static 'img/plug.jpg'%} " alt=""></li>
            <li><img class="img-fluid" src=" {% static 'img/plug.jpg'%} " alt=""></li>
            <li><img class="img-fluid" src=" {% static 'img/plug.jpg'%} " alt=""></li>
            <li><img class="img-fluid" src=" {% static 'img/plug.jpg'%} " alt=""></li>
            <li><img class="img-fluid" src=" {% static 'img/plug.jpg'%} " alt=""></li>
          </ul>
        </div>
      </div>
      <div class="col-lg-2 col-md-6 col-sm-6">
        <div class="single-footer-widget">
          <h6>{% translate 'Waiting for you !' %}</h6>
          <p>{% translate 'Address' %}:</p>
          <p>{% translate 'Tula - st. Magic d39 ' %}</p>
          <p id="date">{% translate 'Now year' %} {% now "Y"%}</p>
        </div>
      </div>
    </div>
  </div>
</footer>

lyceum/templates/include/form.html
{% load i18n %}

{% for field in form %}
<div class="row justify-content-center">
  <div class="col-md-4 mb-4">
    <div class="form-group"> <label class="mr-3" for="{{ field.id_for_label }}">{{ field.label }}</label>{{ field }}
      {% for error in field.errors %}
      <div class="help-block with-errors text-danger">{{ error|safe }}</div>
      {% endfor %}
    </div>
  </div>
</div>
{% endfor %}

lyceum/templates/include/header.html
{% load static %}
{% load i18n %}

<header class="header_area">
  <div class="main_menu">
    <nav class="navbar navbar-expand-lg navbar-light">
      <div class="container box_1620">
        <!-- Brand and toggle get grouped for better mobile display -->{% with request.resolver_match.view_name as view_name %}
        <div class="nav-item {% if view_name == 'homepage:home' %}active{% endif %}"> <a class="navbar-brand logo_h" href=" {% url 'homepage:home' %} "><img
                        src="{% static 'img/svg/cat-logo.svg'%}" width="88" alt=""></a> </div> <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
          <ul class="nav navbar-nav menu_nav justify-content-center">
            <li class="nav-item {% if view_name == 'homepage:home' %}active{% endif %}"><a class="nav-link" href=" {% url 'homepage:home' %} "><span>{% translate 'Home' %}</span></a></li>
            <li class="nav-item {% if view_name == 'catalog:item_list' %}active{% endif %} "><a class="nav-link" href=" {% url 'catalog:item_list' %} "><span>{% translate 'Catalog' %}</span></a></li>
            <li class="nav-item {% if view_name == 'about:description' %}active {% endif %}"><a class="nav-link" href=" {% url 'about:description' %} "><span>{% translate 'About' %}</span></a></li>
            <li class="nav-item {% if view_name == 'feedback:feedback' %}active {% endif %}"><a class="nav-link" href=" {% url 'feedback:feedback' %} "><span>{% translate 'Feedback' %}</span></a></li>
            {% if user.is_superuser %}
            <li class="nav-item"><a href="{% url 'admin:index' %}" type="button" class="nav-link admin-btn"><span>{% translate 'Admin' %}</span></a></li>
            {% endif %}
          </ul> {% endwith %}
          <ul class="nav navbar-nav navbar-right navbar-social">
            {% if request.user.is_authenticated %}
              <li><a class="btn btn-success" href="{% url 'users:profile' %}">{% translate 'My Profile' %}</a></li>
              <li><a class="btn btn-dark" href="{% url 'users:logout' %}">{% translate 'Logout' %}</a></li>
            {% else %}
              <li><a class="btn btn-primary" href="{% url 'users:login' %}">{% translate 'Login' %}</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
  </div>
</header>

lyceum/templates/include/item_card.html
{% load static %}
{% load i18n %}

<div class="single-recent-blog-post card-view p-3">
  <div class="thumb"><img class="card-img rounded-0" src="{{ item.main_image.image.url }}" alt="#">
  </div>
  <div class="details mt-20">
    <a href="{% url 'catalog:item_detail' id=item.id %}">
      <h3>{{ item.name }}</h3>
    </a>
    {% with request.resolver_match.view_name as view_name %}
      {% if view_name != 'catalog:item_list' %}<p class="tag-list-inline">Category: <a href="#">{{ item.category.name }}</a></p>{% endif %}
    {% endwith %}
    <div class="card-text">
      <p>{{ item.text|safe|truncatewords:10 }}</p>
    </div>
    <p class="tag-list-inline">{% translate 'Tags' %}: {% for tag in item.tags.all %}{% if forloop.last %}<a href="#">{{ tag.name }}</a> {% else %} <a href="#">{{ tag.name }}</a>, {% endif %} {% endfor %}
    <div class="button__wrapper">
    <a class="button" href="{% url 'catalog:item_detail' id=item.id %}">{% translate 'Read More'%} <i class="ti-arrow-right"></i></a></div>
  </div>
</div>

lyceum/templates/include/sidebar.html
{% load static %}
{% load i18n %}

<!-- Start Blog Post Siddebar -->
<div class="col-lg-4 sidebar-widgets">
  <div class="widget-wrap">
    <div class="single-sidebar-widget post-category-widget">
      <h4 class="single-sidebar-widget__title">{% translate 'Interesting offers ' %}</h4>
      <ul class="cat-list mt-20">
        <li>
          <a href="{% url 'catalog:new_item_list'%}" class="d-flex justify-content-between">
            <p>{% translate 'New' %}</p>
          </a>
        </li>
        <li>
          <a href="{% url 'catalog:friday_item_list'%}" class="d-flex justify-content-between">
            <p>{% translate 'Friday' %}</p>
          </a>
        </li>
        <li>
          <a href="{% url 'catalog:unchecked_item_list'%}" class="d-flex justify-content-between">
            <p>{% translate 'Unchecked' %}</p>
          </a>
        </li>
      </ul>
    </div>
    <div class="single-sidebar-widget newsletter-widget">
      <h4 class="single-sidebar-widget__title">{% translate 'List of users' %}</h4>
      <div class="form-group mt-30">
      </div><a href="{% url 'users:users_list' %}" class="bbtns d-block mt-20 w-100 text-center">{% translate 'Look' %}</a>
    </div>
  </div>
</div>
<!-- End Blog Post Siddebar -->