lyceum/about/urls.py
from django.urls import path

from about import views

app_name = "about"
urlpatterns = [
    path("", views.DescriptionView.as_view(), name="description"),
]

lyceum/feedback/urls.py
from django.urls import path

from feedback import views

app_name = "feedback"
urlpatterns = [
    path("", views.FeedbackView.as_view(), name="feedback"),
]

lyceum/lyceum/urls.py
from django.conf import settings
from django.conf.urls.static import static
import django.contrib.admin
import django.contrib.auth.urls
import django.urls

import about.urls
import catalog.urls
import download.urls
import feedback.urls
import homepage.urls
import statistic.urls
import users.urls

urlpatterns = [
    django.urls.path("", django.urls.include(homepage.urls)),
    django.urls.path("about/", django.urls.include(about.urls)),
    django.urls.path("feedback/", django.urls.include(feedback.urls)),
    django.urls.path("catalog/", django.urls.include(catalog.urls)),
    django.urls.path("download/", django.urls.include(download.urls)),
    django.urls.path("statistic/", django.urls.include(statistic.urls)),
    django.urls.path("admin/", django.contrib.admin.site.urls),
    django.urls.path("auth/", django.urls.include(users.urls)),
    django.urls.path("auth/", django.urls.include(django.contrib.auth.urls)),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar

    urlpatterns.append(
        django.urls.path("__debug__/", django.urls.include(debug_toolbar.urls))
    )

lyceum/feedback/models.py
from django.db import models

import core.models as core


class Feedback(
    core.CreatedDateBaseModel,
    core.TextMessageModel,
):
    class Status(models.TextChoices):
        accepted = "c", "accepted"
        processing = "b", "processing"
        completed = "a", "completed"

    status = models.CharField(
        "status",
        max_length=2,
        default=Status.accepted,
        choices=Status.choices,
        help_text="Mail status",
    )

    class Meta:
        ordering = ("created_at",)
        verbose_name = "mail"
        verbose_name_plural = "mails"


class FeedbackUserData(models.Model):
    email = models.EmailField(
        "mail",
        max_length=254,
        help_text="you need to enter a corrective email address",
    )

    feedback = models.OneToOneField(
        Feedback,
        on_delete=models.CASCADE,
        verbose_name="feedback",
        null=True,
        blank=True,
        help_text="Feedback",
    )

    class Meta:
        verbose_name = "user data"
        verbose_name_plural = "users data"
        default_related_name = "data_user"


class FeedbackFiles(models.Model):
    def saving_path(self, name):
        return f"uploads/{self.feedback.id}/{name}"

    files = models.FileField(
        "files",
        upload_to=saving_path,
        null=True,
        default=None,
        help_text="attach files",
    )

    feedback = models.ForeignKey(
        Feedback,
        on_delete=models.CASCADE,
        verbose_name="feedback",
        default=None,
        help_text="Attach files",
    )

    class Meta:
        verbose_name = "feedback files"
        verbose_name_plural = "feedback files"
        default_related_name = "files"

lyceum/feedback/forms.py
import django.forms

import feedback.models


class FeedbackForm(django.forms.Form):
    email = django.forms.EmailField(label="Email *", help_text="Enter your email")
    text = django.forms.CharField(
        label="Message *",
        help_text="Write what you think about our company =)",
    )
    files = django.forms.FileField(
        required=False,
        label="Files",
        help_text="Download file",
    )

    def save(self, file_list: list) -> bool:
        data = self.cleaned_data

        feedback_data = feedback.models.Feedback(text=data["text"])
        data_user = feedback.models.FeedbackUserData(
            email=data["email"], feedback=feedback_data
        )

        feedback_data.save()
        data_user.save()

        if data["files"] is not None:
            for file in file_list:
                feedback_files = feedback.models.FeedbackFiles(
                    files=file, feedback=feedback_data
                )
                feedback_files.save()

lyceum/feedback/views.py
from django.conf import settings
from django.contrib import messages
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import FormView

import feedback.forms as forms


class FeedbackView(FormView):
    form_class = forms.FeedbackForm
    template_name = "feedback/feedback.html"
    success_url = reverse_lazy("feedback:feedback")

    def form_valid(self, form: forms.FeedbackForm) -> HttpResponseRedirect:
        try:
            form.save(self.request.FILES.getlist("files"))

            send_mail(
                "Feedback",
                f'Thanks for the feedback <br> Your message '
                f'- « {form.cleaned_data["text"]} »',
                settings.MAIL_SENDER,
                [f'{form.cleaned_data["email"]}'],
                fail_silently=False,
            )

            messages.success(
                self.request, "Thank you for the confidential communication =)"
            )
        except Exception:
            messages.success(self.request, "Write error =(")
        return super().form_valid(form)

lyceum/templates/feedback/feedback.html
{% extends 'layouts/layout.html' %}
{% load static %}
{% load i18n %}

{% block title %}
<title>{% translate 'Fluffies feedback'%}</title>
{% endblock %}

{% block content %}
<div class="main__conteiner">
  <section class="mb-30px">
    <div class="container">
      <div class="hero-banner-about hero-banner--sm">
        <div class="hero-banner__content-about">
          <h1>{% translate 'Feedback'%}</h1>
        </div>
      </div>
    </div>
  </section>
  <!--================ Start Blog Post Area =================-->
  <div class="blog-post-area section-margin">
    <div class="container">
      {% if messages %}
      <ul class="messages">
        {% for message in messages %}
          <li class="text-success font-weight-bold text-center display-6 m-4">{{ message }}</li>
        {% endfor %}
      </ul>
      {% endif %}

      <form class="basic-form" id="contact-form" action="{% url 'feedback:feedback' %}" method="post" role="form" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="controls text-center">
          <div class="row justify-content-center">
            <div class="col-md-6">
              <div class="form-group"> <label for="form_email">{{ form.fields.email.label }}</label> <input id="form_email" type="email" name="email" class="form-control" value="{{ form.data.email }}" placeholder="{{ form.fields.email.help_text }}" required="required" data-error="Valid email is required.">
                <div class="help-block with-errors text-danger">{{ form.email.errors }}</div>
              </div>
            </div>
          </div>
          <div class="row justify-content-center">
            <div class="col-md-6">
              <div class="form-group"> <label for="form_message">{{ form.fields.text.label }}</label> <textarea id="form_message" name="text" class="form-control" placeholder="{{ form.fields.text.help_text }}" rows="4" required="required" data-error="Please,leave us a message.">{{ form.data.text }}</textarea>
                <div class="help-block with-errors text-danger">{{ form.text.errors }}</div>
              </div>
            </div>
          </div>
          <div class="row justify-content-center">
            <div class="col-md-6 mb-1">
              <div class="form-group">
                <label class="m-3" for="id_files">{{ form.fields.files.label }}</label><input type="file" name="files" multiple id="id_files"><br><span class="helptext">{{ form.fields.files.help_text }}</span>
              </div>
            </div>
            <div class="col-md-12"> <input type="submit" class="btn btn-success btn-send" value="Send message"> </div>
          </div>
        </div>
      </form>
    </div>
  </div>
</div> {% endblock %}