lyceum/about/urls.py
from django.urls import path

from about import views

app_name = "about"
urlpatterns = [
    path("", views.DescriptionView.as_view(), name="description"),
]

lyceum/lyceum/urls.py
from django.conf import settings
from django.conf.urls.static import static
import django.contrib.admin
import django.contrib.auth.urls
import django.urls

import about.urls
import catalog.urls
import download.urls
import feedback.urls
import homepage.urls
import statistic.urls
import users.urls

urlpatterns = [
    django.urls.path("", django.urls.include(homepage.urls)),
    django.urls.path("about/", django.urls.include(about.urls)),
    django.urls.path("feedback/", django.urls.include(feedback.urls)),
    django.urls.path("catalog/", django.urls.include(catalog.urls)),
    django.urls.path("download/", django.urls.include(download.urls)),
    django.urls.path("statistic/", django.urls.include(statistic.urls)),
    django.urls.path("admin/", django.contrib.admin.site.urls),
    django.urls.path("auth/", django.urls.include(users.urls)),
    django.urls.path("auth/", django.urls.include(django.contrib.auth.urls)),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar

    urlpatterns.append(
        django.urls.path("__debug__/", django.urls.include(debug_toolbar.urls))
    )

lyceum/statistic/urls.py
from django.urls import path

from statistic import views

app_name = "statistic"
urlpatterns = [
    path(
        "chosen/",
        views.UserItemListView.as_view(),
        name="user_item_list",
    ),
    path(
        "<int:id>",
        views.UserStatisticView.as_view(),
        name="user_detail_statistics",
    ),
]

lyceum/users/urls.py
from django.contrib.auth.decorators import login_required
import django.contrib.auth.views
import django.urls

import users.views

app_name = "users"
urlpatterns = [
    django.urls.path(
        "register/",
        users.views.Register.as_view(),
        name="register",
    ),
    django.urls.path(
        "activate/<str:name>/",
        users.views.ActivateUsers.as_view(),
        name="activate",
    ),
    django.urls.path(
        "recovery/<str:name>/",
        users.views.UserRecovery.as_view(),
        name="recovery",
    ),
    django.urls.path(
        "user_list/",
        users.views.UsersList.as_view(),
        name="users_list",
    ),
    django.urls.path(
        "user_detail/<int:id>/",
        users.views.UsersDetail.as_view(),
        name="user_detail",
    ),
    django.urls.path(
        "profile/",
        login_required(users.views.UsersProfile.as_view()),
        name="profile",
    ),
    django.urls.path(
        "login/",
        django.contrib.auth.views.LoginView.as_view(
            template_name="users/login.html",
        ),
        name="login",
    ),
    django.urls.path(
        "logout/",
        django.contrib.auth.views.LogoutView.as_view(
            template_name="users/logout.html",
        ),
        name="logout",
    ),
    django.urls.path(
        "password_change/",
        django.contrib.auth.views.PasswordChangeView.as_view(
            template_name="users/password_change_form.html",
        ),
        name="password_change",
    ),
    django.urls.path(
        "password_change/done/",
        django.contrib.auth.views.PasswordChangeDoneView.as_view(
            template_name="users/password_change_done.html",
        ),
        name="password_change_done",
    ),
    django.urls.path(
        "password_reset/",
        django.contrib.auth.views.PasswordResetView.as_view(
            template_name="users/password_reset.html",
        ),
        name="password_reset",
    ),
    django.urls.path(
        "password_reset/done/",
        django.contrib.auth.views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html",
        ),
        name="password_reset_done",
    ),
    django.urls.path(
        "reset/<uidb64>/<token>/",
        django.contrib.auth.views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
        ),
        name="password_reset_confirm",
    ),
    django.urls.path(
        "reset/done/",
        django.contrib.auth.views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html",
        ),
        name="password_reset_complete",
    ),
]

lyceum/users/models.py
from django.contrib.auth.models import User
from django.db import models

import core.models
from users.managers import UserProfileManager


class Profile(core.models.ImageBaseModel):
    def saving_path(self, name: str) -> str:
        return f"uploads/user_image/{self.user.id}/{name}"

    login_failed_count = models.PositiveSmallIntegerField(
        "number of failed logins",
        default=0,
        help_text="number of failed logins",
    )

    account_blocking_date = models.DateTimeField(
        "account blocking date",
        default=None,
        null=True,
        blank=True,
        help_text="Account lockout date",
    )

    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        verbose_name="user",
        help_text="user",
    )

    birthday = models.DateField(
        "birthday", blank=True, null=True, help_text="Enter date of birth"
    )

    image = models.ImageField(
        "profile picture",
        upload_to=saving_path,
        blank=True,
        null=True,
        help_text="Enter profile picture",
    )

    coffee_count = models.PositiveSmallIntegerField(
        "coffee count",
        default=0,
        help_text="Number of user requests for coffee",
    )

    class Meta:
        verbose_name = "additional field"
        verbose_name_plural = "additional fields"
        default_related_name = "profile"


class UserProfileProxy(User):
    objects = UserProfileManager()

    class Meta:
        proxy = True
        ordering = (User.date_joined.field.name,)

lyceum/users/forms.py
from django import forms
import django.contrib.auth.forms
from django.contrib.auth.models import User
from django.db.models import Q

from users.models import Profile
from users.models import UserProfileProxy


class CustomUserCreationForm(django.contrib.auth.forms.UserCreationForm):
    email = forms.EmailField(
        label="Email", max_length=254, help_text="Enter email please"
    )

    class Meta(django.contrib.auth.forms.UserCreationForm.Meta):
        model = UserProfileProxy
        fields = ("username", "email")

    def clean_email(self) -> str:
        normalized_email = UserProfileProxy.objects.__class__.normalize_email(
            self.cleaned_data.get(User.email.field.name)
        )
        is_email_unique = UserProfileProxy.objects.filter(
            ~Q(pk=self.instance.id),
            email=normalized_email,
        ).exists()
        if is_email_unique:
            self.add_error(
                UserProfileProxy.email.field.name,
                "User with this email address is registered",
            )
        return normalized_email


class CustomUserChangeForm(django.contrib.auth.forms.UserChangeForm):
    def __init__(self, *args, **kwargs):
        super(CustomUserChangeForm, self).__init__(*args, **kwargs)

    password = None

    class Meta:
        model = UserProfileProxy
        field_classes = {"username": django.contrib.auth.forms.UsernameField}
        fields = [
            UserProfileProxy.email.field.name,
            UserProfileProxy.username.field.name,
            UserProfileProxy.first_name.field.name,
            UserProfileProxy.last_name.field.name,
        ]

    def clean_email(self) -> str:
        normalized_email = UserProfileProxy.objects.__class__.normalize_email(
            self.cleaned_data.get(User.email.field.name)
        )
        is_email_unique = UserProfileProxy.objects.filter(
            ~Q(pk=self.instance.id),
            email=normalized_email,
        ).exists()
        if is_email_unique:
            self.add_error(
                UserProfileProxy.email.field.name,
                "User with this email address is registered",
            )
        return normalized_email


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = [
            Profile.coffee_count.field.name,
            Profile.birthday.field.name,
            Profile.image.field.name,
        ]
        widgets = {
            Profile.coffee_count.field.name: forms.TextInput(
                attrs={"readonly": "readonly"}
            ),
        }

lyceum/users/views.py
from datetime import timedelta

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.http import HttpRequest
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.utils import timezone
from django.views import View

import users.forms
from users.models import Profile
from users.models import UserProfileProxy


class Register(View):
    template_name = "users/signup.html"

    def get(self, request: HttpRequest) -> HttpResponse | HttpResponseRedirect:
        context = {"form": users.forms.CustomUserCreationForm()}
        return render(request, self.template_name, context)

    def post(self, request: HttpRequest) -> HttpResponse:
        form = users.forms.CustomUserCreationForm(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = settings.DEFAULT_USER_ACTIVITY
            user.save()
            profile = Profile(user=user)
            profile.save()

            if not settings.DEFAULT_USER_ACTIVITY:
                absolute_url = self.request.build_absolute_uri(
                    reverse_lazy(
                        "users:activate",
                        args=[user.username],
                    )
                )
                send_mail(
                    "Email verification",
                    f"Thank you for registering on our website! <br>"
                    f"Profile activation link! <br>"
                    f"- « {absolute_url}",
                    settings.MAIL_SENDER,
                    [f'{form.cleaned_data["email"]}'],
                    fail_silently=False,
                )

            return redirect("homepage:home")
        context = {"form": form}
        return render(request, self.template_name, context)


class ActivateUsers(View):
    template_name = "users/activate.html"

    def get(self, request: HttpRequest, name: str) -> HttpResponse:
        context = {}

        user = get_object_or_404(User, username=name)
        if (
            user.date_joined < timezone.now() - timedelta(hours=12)
            and not user.is_active
        ):
            user.delete()
            messages.error(request, "Overdue =(")
        elif user.is_active is False:
            user.is_active = True
            user.save()
            messages.success(request, "Your account has been" " successfully activated")
        else:
            messages.success(request, "This user is already activated")

        return render(request, self.template_name, context)


class UsersList(View):
    template_name = "users/user_list.html"

    def get(self, request: HttpRequest) -> HttpResponse:
        users = UserProfileProxy.objects.get_user_list()
        context = {"users": users}
        return render(request, self.template_name, context)


class UsersDetail(View):
    template_name = "users/user_detail.html"

    def get(self, request, id: int) -> HttpResponse:
        user = get_object_or_404(UserProfileProxy.objects.get_user_detail(), pk=id)
        context = {"current_user": user}
        return render(request, self.template_name, context)


class UsersProfile(View):
    template_name = "users/profile.html"

    def get(self, request: HttpRequest) -> HttpResponse:
        user = request.user
        form = users.forms.CustomUserChangeForm(instance=user)
        profile_form = users.forms.ProfileForm(instance=user.profile)
        context = {"form": form, "profile_form": profile_form}
        return render(request, self.template_name, context)

    def post(self, request: HttpRequest) -> HttpResponse:
        user = request.user

        form = users.forms.CustomUserChangeForm(request.POST, instance=user)
        profile_form = users.forms.ProfileForm(
            request.POST, request.FILES, instance=user.profile
        )

        if form.is_valid() and profile_form.is_valid():
            form.save()
            profile_form.save()

        context = {"form": form, "profile_form": profile_form}
        return render(request, self.template_name, context)


class UserRecovery(View):
    template_name = "users/recovery.html"

    def get(self, request: HttpRequest, name: str) -> HttpResponse:
        user = get_object_or_404(User, username=name)
        if (
            user.profile.account_blocking_date is not None
            and user.profile.account_blocking_date > timezone.now() + timedelta(days=7)
            and not user.is_active
        ):
            user.delete()
            messages.error(request, "User deleted")
        elif user.is_active is False:
            user.is_active = True
            user.profile.login_failed_count = 0
            user.profile.account_blocking_date = None
            user.profile.save()
            user.save()
            messages.success(request, "Account restored!")
        else:
            messages.success(request, "Account does not require recovery")

        return render(request, self.template_name)

lyceum/templates/users/activate.html
{% extends 'layouts/layout.html' %}
{% load static %}
{% load i18n %}

{% block title %}
<title>{% translate 'Profile activation'%}</title>
{% endblock %}

{% block content %}
<section class="mb-3">
  <div class="container">
    {% if messages %}
      <ul class="messages">
        {% for message in messages %}
          <li class="text-success font-weight-bold text-center display-4 m-4">{{ message }}</li>
        {% endfor %}
      </ul>
      {% endif %}
  </div>
</section>
<!--================ Start Blog Post Area =================-->
{% endblock %}

lyceum/templates/users/login.html
{% extends 'layouts/layout.html' %}
{% load static %}
{% load i18n %}

{% block title %}
<title>{% translate 'Login'%}</title>
{% endblock %}

{% block content %}
<section class="mb-3">
  <div class="container">
    <h1 class="text-center">
      {% translate 'Login to your account'%}
    </h1>
  </div>
</section>
<!--================ Start Blog Post Area =================-->
<div class="blog-post-area section-margin mt-4">
  <div class="container">
    <section class="row justify-content-center">
      <div class="col-lg-12">
          <form class="basic-form mb-1" method="post" role="form">
            {% csrf_token %}
            <div class="text-center text-danger m-3">{{ form.non_field_errors }}</div>
            <div class="controls text-center">
              {% include 'include/form.html' %}
              <div class="row justify-content-center">
                <div class="col-md-12"> <input type="submit" class="btn btn-success btn-send" value="{% translate 'Sing in'%}"> </div>
              </div>
            </div>
          </form>
      </div>
      <div class="col-md-12 row justify-content-center">
        <a class="btn btn-primary m-3" href="{% url 'users:register' %}">{% translate 'Register' %}</a>
      </div>
      <div class="col-md-12 row justify-content-center">
        <a class="btn btn-primary" href="{% url 'users:password_reset' %}">{% translate 'Forgot your password' %}</a>
      </div>
    </section>
  </div>
</div>
{% endblock %}

lyceum/templates/users/logout.html
{% extends 'layouts/layout.html' %}
{% load static %}
{% load i18n %}

{% block title %}
<title>{% translate 'Logout'%}</title>
{% endblock %}

{% block content %}
<section class="mb-3">
  <div class="container">
    <h1 class="text-center text-success">
      {% translate 'You are logged out!'%}
    </h1>
  </div>
</section>
<!--================ Start Blog Post Area =================-->
{% endblock %}

lyceum/templates/users/password_change_form.html
{% extends 'layouts/layout.html' %}
{% load static %}
{% load i18n %}

{% block title %}
<title>{% translate 'Password change'%}</title>
{% endblock %}

{% block content %}
<section class="mb-3">
  <div class="container">
    <h1 class="text-center">
      {% translate 'Сhange password'%}
    </h1>
  </div>
</section>
<!--================ Start Blog Post Area =================-->
<div class="blog-post-area section-margin mt-4">
  <div class="container">
    <section class="row">
      <div class="col-lg-12">
        <form class="basic-form mb-1" method="post" role="form">
          {% csrf_token %}
          <div class="text-center text-danger m-3">{{ form.non_field_errors }}</div>
          <div class="controls text-center">
            {% include 'include/form.html' %}
            <div class="row justify-content-center">
              <div class="col-md-12"> <input type="submit" class="btn btn-success btn-send" value="{% translate 'Change password'%}"> </div>
            </div>
          </div>
        </form>
      </div>
    </section>
  </div>
</div>
{% endblock %}

lyceum/templates/users/password_reset.html
{% extends 'layouts/layout.html' %}
{% load static %}
{% load i18n %}

{% block title %}
<title>{% translate 'Password recovery'%}</title>
{% endblock %}

{% block content %}
<section class="mb-3">
  <div class="container">
    <h1 class="text-center">
      Send us your email address to change your password
    </h1>
  </div>
</section>
<!--================ Start Blog Post Area =================-->
<div class="blog-post-area section-margin mt-4">
  <div class="container">
    <section class="row">
      <div class="col-lg-12">
        <form class="basic-form mb-1" method="post" role="form">
          {% csrf_token %}
          <div class="text-center text-danger m-3">{{ form.non_field_errors }}</div>
          <div class="controls text-center">
            {% include 'include/form.html' %}
            <div class="row justify-content-center">
              <div class="col-md-12"> <input type="submit" class="btn btn-success btn-send" value="{% translate 'Send'%}"> </div>
            </div>
          </div>
        </form>
      </div>
    </section>
  </div>
</div>
{% endblock %}

lyceum/templates/users/password_reset_complete.html
{% extends 'layouts/layout.html' %}
{% load static %}
{% load i18n %}

{% block title %}
<title>{% translate 'Password recovery'%}</title>
{% endblock %}

{% block content %}
<section class="mb-3">
  <div class="container">
    <h1 class="text-center text-success">
      {% translate 'Your password has been set. You may go ahead and log in now !'%} <a href="{% url 'users:login' %}">{% translate 'Sing in'%}</a>
    </h1>
  </div>
</section>
<!--================ Start Blog Post Area =================-->
{% endblock %}

lyceum/templates/users/password_reset_confirm.html
{% extends 'layouts/layout.html' %}
{% load static %}
{% load i18n %}

{% block title %}
<title>{% translate 'Password recovery'%}</title>
{% endblock %}

{% block content %}
<section class="mb-3">
  <div class="container">
    <h1 class="text-center">
      Confirm password reset
    </h1>
  </div>
</section>
<!--================ Start Blog Post Area =================-->
<div class="blog-post-area section-margin mt-4">
  <div class="container">
    <section class="row">
      <div class="col-lg-12">
        <form class="basic-form mb-1" method="post" role="form">
          {% csrf_token %}
          <div class="text-center text-danger m-3">{{ form.non_field_errors }}</div>
          <div class="controls text-center">
            {% include 'include/form.html' %}
            <div class="row justify-content-center">
              <div class="col-md-12"> <input type="submit" class="btn btn-success btn-send" value="{% translate 'Change password'%}"> </div>
            </div>
          </div>
        </form>
      </div>
    </section>
  </div>
</div>
{% endblock %}

lyceum/templates/users/password_reset_done.html
{% extends 'layouts/layout.html' %}
{% load static %}
{% load i18n %}

{% block title %}
<title>{% translate 'Password recovery'%}</title>
{% endblock %}

{% block content %}
<section class="mb-3">
  <div class="container">
    <h1 class="text-center">{% translate 'Password recovery'%}</h1>
    <h4 class="text-center text-success">
      {% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly. If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.'%}
    </h4>
  </div>
</section>
<!--================ Start Blog Post Area =================-->
{% endblock %}

lyceum/templates/users/profile.html
{% extends 'layouts/layout.html' %}
{% load static %}
{% load i18n %}

{% block title %}
<title>{% translate 'Your profile'%}</title>
{% endblock %}

{% block content %}
<section class="mb-3">
  <div class="container">
    <h1 class="text-center">
      {% translate 'Your profile' %}
    </h1>
  </div>
</section>
<!--================ Start Blog Post Area =================-->
<div class="blog-post-area section-margin mt-4">
  <div class="container">
    <section class="row justify-content-center">
      <div class="col-lg-12">
        <form class="basic-form" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% if user.profile.image %}
        <div class="text-center">
          <h2>{% translate 'Your profile photo'%}</h2>
          <img class="border-info profile-image" src="{{user.profile.get_image_300x300.url}}" alt="">
        </div>
        {% endif %}
        <div class="text-center text-danger m-3">{{ form.non_field_errors }}</div>
        <div class="controls text-center">
          {% for field in form %}
          <div class="row justify-content-center">
            <div class="col-md-4 mb-4">
              <div class="form-group"> <label class="mr-3" for="{{ field.id_for_label }}">{{ field.label }}</label>{{ field }}
                {% for error in field.errors %}
                  <div class="help-block with-errors text-danger">{{ error|safe }}</div>
                {% endfor %}
              </div>
            </div>
          </div>
          {% endfor %}

          {% for field in profile_form %}
          <div class="row justify-content-center">
            <div class="col-md-4 mb-4">
              <div class="form-group"> <label class="mr-3" for="{{ field.id_for_label }}">{{ field.label }}</label>{{ field }}
                {% for error in field.errors %}
                  <div class="help-block with-errors text-danger">{{ error|safe }}</div>
                {% endfor %}
              </div>
            </div>
          </div>
          {% endfor %}
          <div class="row justify-content-center">
            <div class="col-md-12"> <input type="submit" class="btn btn-success btn-send" value="{% translate 'Update your profile' %}"> </div>
          </div>
        </div>
      </form>
      </div>
      <div class="row actions justify-content-center">
        <div class="row-item m-3">
          <h2 class="mb-1 text-center">{% translate 'Your statistic' %}</h2>
          <ul class="list-group">
            <li class="list-group-item"><a class="btn btn-info w-100" id="stat_user" href="{% url 'statistic:user_item_list' %}">{% translate 'List of rated items' %}</a></li>
            <li class="list-group-item"><a class="btn btn-info w-100" id="stat_items" href="{% url 'statistic:user_detail_statistics' id=user.id %}">{% translate 'Most favorite' %}</a></li>
          </ul>
        </div>
        <div class="row-item m-3">
          <h2 class="mb-1 text-center">{% translate 'Actions' %}</h2>
          <ul class="list-group">
            <li class="list-group-item"><button class="btn btn-success w-100" type="button" id="coffee_count">{% translate 'Drink coffee' %}</button></li>
            <li class="list-group-item"><a class="btn btn-success w-100" href="{% url 'users:password_change' %}">{% translate 'Change password' %}</a></li>
          </ul>
        </div>
      </div>
    </section>
  </div>
</div>
{% endblock %}

lyceum/templates/users/recovery.html
{% extends 'layouts/layout.html' %}
{% load static %}
{% load i18n %}

{% block title %}
<title>{% translate 'Profile activation'%}</title>
{% endblock %}

{% block content %}
<section class="mb-3">
  <div class="container">
    {% if messages %}
      <ul class="messages">
        {% for message in messages %}
          <li class="text-success font-weight-bold text-center display-4 m-4">{{ message }}</li>
        {% endfor %}
      </ul>
      {% endif %}
  </div>
</section>
<!--================ Start Blog Post Area =================-->
{% endblock %}

lyceum/templates/users/register.html
{% extends 'layouts/layout.html' %}
{% load static %}
{% load i18n %}

{% block title %}
<title>{% translate 'Fluffies '%}</title>
{% endblock %}

{% block content %}
<section class="mb-3">
  <div class="container">
    <h1 class="text-center">
      Register to your account
    </h1>
  </div>
</section>
<!--================ Start Blog Post Area =================-->
<div class="blog-post-area section-margin mt-4">
  <div class="container">
    <section class="row">
      <div class="col-lg-12">
        <form action="" method="post" role="form">
        {% csrf_token %}
        <div class="controls text-center">
          {% for field in form %}
          <div class="row justify-content-center">
            <div class="col-md-4 mb-4">
              <div class="form-group"> <label class="mr-3" for="{{ field.id_for_label }}">{{ field.label }}</label>{{ field }}
                <div class="help-block with-errors text-danger">{{ field.errors }}</div>
              </div>
            </div>
          </div>
          {% endfor %}
          <div class="row justify-content-center">
            <div class="col-md-12"> <input type="submit" class="btn btn-success btn-send" value="Register"> </div>
          </div>
        </div>
      </form>
      </div>
    </section>
  </div>
</div>
{% endblock %}

lyceum/templates/users/signup.html
{% extends 'layouts/layout.html' %}
{% load static %}
{% load i18n %}

{% block title %}
<title>{% translate 'Registration'%}</title>
{% endblock %}

{% block content %}
<section class="mb-3">
  <div class="container">
    <h1 class="text-center">
      {% translate 'Register to your account'%}
    </h1>
  </div>
</section>
<!--================ Start Blog Post Area =================-->
<div class="blog-post-area section-margin mt-4">
  <div class="container">
    <section class="row">
      <div class="col-lg-12">
        <form class="basic-form mb-1" method="post" role="form">
          {% csrf_token %}
          <div class="text-center text-danger m-3">{{ form.non_field_errors }}</div>
          <div class="controls text-center">
            {% include 'include/form.html' %}
            <div class="row justify-content-center">
              <div class="col-md-12"> <input type="submit" class="btn btn-success btn-send" value="{% translate 'Sing up'%}"> </div>
            </div>
          </div>
        </form>
      </div>
    </section>
  </div>
</div>
{% endblock %}

lyceum/templates/users/user_detail.html
{% extends 'layouts/layout.html' %}
{% load static %}
{% load i18n %}

{% block title %}
<title>{% translate 'User'%} {{current_user.username}}</title>
{% endblock %}

{% block content %}

<div class="container rounded bg-white mb-1">
  <h1 class="text-center mb-5 border-bottom">{% translate 'Profile user'%}</h1>
  <div class="row justify-content-center">
    <div class="col-6 p-3">
      <div class="m-3 text-center"><img class="card-img" src="{% if current_user.profile.image %} {{current_user.profile.get_image_300x300.url}} {% else %} {% static 'img/plug.jpg' %}{% endif %}" alt="">
      </div>
      <div class="text-center">
        <h2>{% translate 'Username'%} - <span>{{current_user.username}}</span></h2>
      </div>
      <div class="row flex-nowrap mb-1">
        <div class="text-center col-6 border">
        <h2>{% translate 'First name'%}</h2>
        {% if current_user.first_name %} {{current_user.first_name}} {% else %} <p class="no-info">{% translate 'no information'%}</p> {% endif %}
        </div>
        <div class="text-center col-6 border">
          <h2>{% translate 'Last name'%}</h2>
          {% if current_user.last_name %} {{current_user.last_name}} {% else %} <p class="no-info">{% translate 'no information'%}</p> {% endif %}
        </div>
      </div>
      <div class="row flex-nowrap mb-1">
        <div class="text-center col-6 border">
        <h2>Email</h2>
        {% if current_user.email %} {{current_user.email}} {% else %} <p class="no-info">{% translate 'no information'%}</p> {% endif %}
        </div>
        <div class="text-center col-6 border">
          <h2>{% translate 'Coffee count'%}</h2>
          {% if current_user.profile.coffee_count %} {{current_user.profile.coffee_count}} {% else %} <p class="no-info">{% translate 'no information'%}</p> {% endif %}
        </div>
      </div>
      <div class="row flex-nowrap mb-1 justify-content-center">
        <div class="text-center col-6 border">
        <h2>{% translate 'Birthday'%}</h2>
        {% if current_user.profile.birthday %} {{current_user.profile.birthday}} {% else %} <p class="no-info">{% translate 'no information'%}</p> {% endif %}
        </div>
      </div>
      <div class="row justify-content-center m-2">
        <h2 class="text-center"><a href="{% url 'statistic:user_detail_statistics' id=user.id%}">{% translate 'User ratings'%}</a></h2>
      </div>
      <div>
      </div>
    </div>
  </div>
</div>
<!--================ Start Blog Post Area =================-->
{% endblock %}

lyceum/templates/users/user_list.html
{% extends 'layouts/layout.html' %}
{% load static %}
{% load i18n %}

{% block title %}
<title>{% translate 'List of users'%}</title>
{% endblock %}

{% block content %}
<section class="mb-3">
  <div class="container">
    <table class="table m-3">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">{% translate 'Username'%}</th>
          <th scope="col">{% translate 'Email'%}</th>
          <th scope="col">{% translate 'Ratings'%}</th>
        </tr>
      </thead>
      <tbody>
        {% for user in users %}
        <tr>
          <th scope="row"><a href="{% url 'users:user_detail' id=user.id %}">{{user.id}}</a></th>
          <td><a href="{% url 'users:user_detail' id=user.id %}">{{user.username}}</a></td>
          <td>{{user.email}}</td>
          <td><a href="{% url 'statistic:user_detail_statistics' id=user.id%}">{% translate 'User ratings'%}</a></td>
        </tr>
        {% empty %}
        <tr>
          <th scope="row">{% translate 'You are most likely'%}</th>
          <td>{% translate 'the first person'%}</td>
          <td>{% translate 'to come here.'%}</td>
          <td>=(</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</section>
<!--================ Start Blog Post Area =================-->
{% endblock %}