lyceum/about/urls.py
from django.urls import path

from about import views

app_name = "about"
urlpatterns = [
    path("", views.DescriptionView.as_view(), name="description"),
]

lyceum/catalog/urls.py
from django.urls import path
from django.urls import re_path
from django.urls import register_converter

from catalog import converters
from catalog import views

register_converter(converters.MyIntegerConverter, "integer")

app_name = "catalog"
urlpatterns = [
    path(
        "",
        views.ItemListView.as_view(),
        name="item_list",
    ),
    path(
        "new/",
        views.NewItemListView.as_view(),
        name="new_item_list",
    ),
    path(
        "friday/",
        views.FridayItemListView.as_view(),
        name="friday_item_list",
    ),
    path(
        "unchecked/",
        views.UncheckedItemListView.as_view(),
        name="unchecked_item_list",
    ),
    path(
        "<int:id>/",
        views.ItemDetailView.as_view(),
        name="item_detail",
    ),
    re_path(
        r"re/(?P<id>[1-9][0-9]*)/",
        views.ItemDetailView.as_view(),
        name="detail_re",
    ),
    path(
        r"converter/<integer:id>/",
        views.ItemDetailView.as_view(),
        name="detail_converter",
    ),
]

lyceum/download/urls.py
from django.urls import re_path

from download import views

app_name = "download"
urlpatterns = [
    re_path(
        r"(?P<file_name>.*)/$",
        views.DownloadImageView.as_view(),
        name="download_image",
    ),
]

lyceum/lyceum/urls.py
from django.conf import settings
from django.conf.urls.static import static
import django.contrib.admin
import django.contrib.auth.urls
import django.urls

import about.urls
import catalog.urls
import download.urls
import feedback.urls
import homepage.urls
import statistic.urls
import users.urls

urlpatterns = [
    django.urls.path("", django.urls.include(homepage.urls)),
    django.urls.path("about/", django.urls.include(about.urls)),
    django.urls.path("feedback/", django.urls.include(feedback.urls)),
    django.urls.path("catalog/", django.urls.include(catalog.urls)),
    django.urls.path("download/", django.urls.include(download.urls)),
    django.urls.path("statistic/", django.urls.include(statistic.urls)),
    django.urls.path("admin/", django.contrib.admin.site.urls),
    django.urls.path("auth/", django.urls.include(users.urls)),
    django.urls.path("auth/", django.urls.include(django.contrib.auth.urls)),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar

    urlpatterns.append(
        django.urls.path("__debug__/", django.urls.include(debug_toolbar.urls))
    )

lyceum/catalog/models.py
from django.core import validators
from django.db import models

from catalog.managers import ItemManager
import core.models as core


class Category(
    core.NamedBaseModel,
    core.PublishedBaseModel,
    core.SluggedBaseModel,
    core.NormalizedNameBaseModel,
):
    weight = models.PositiveSmallIntegerField(
        "weight",
        default=100,
        validators=[
            validators.MinValueValidator(0, "Minimum number to enter 0"),
            validators.MaxValueValidator(32767, "The maximum number to enter is 32767"),
        ],
    )

    class Meta:
        verbose_name = "category"
        verbose_name_plural = "categories"


class Tag(
    core.NamedBaseModel,
    core.PublishedBaseModel,
    core.SluggedBaseModel,
    core.NormalizedNameBaseModel,
):
    class Meta:
        verbose_name = "tag"
        verbose_name_plural = "tags"
        default_related_name = "tags"


class Item(
    core.NamedBaseModel,
    core.PublishedBaseModel,
    core.CreatedDateBaseModel,
    core.UpdatedDateBaseModel,
    core.TextBaseModel,
):
    objects = ItemManager()

    is_on_main = models.BooleanField("Show on home page", default=False)

    category = models.ForeignKey(
        Category,
        on_delete=models.PROTECT,
        verbose_name="category",
        help_text="The product must have a category.",
    )

    tags = models.ManyToManyField(
        Tag,
        verbose_name="tags",
        help_text="The element must have at least 1 tag.",
    )

    class Meta:
        ordering = ("name",)
        verbose_name = "product"
        verbose_name_plural = "products"
        default_related_name = "items"

    def __str__(self) -> str:
        return self.name[:20]


class MainImageItem(core.NamedBaseModel, core.ImageBaseModel):
    def saving_path(self, name):
        return f"uploads/main_image/{self.items.id}/{name}"

    items = models.OneToOneField(
        Item,
        verbose_name="main image",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        help_text="main image",
    )

    image = models.ImageField(
        "main image",
        upload_to=saving_path,
        help_text="Will be rendered at 300px",
    )

    class Meta:
        verbose_name = "main image"
        verbose_name_plural = "main images"
        default_related_name = "main_image"


class GalleryImagesItem(core.NamedBaseModel, core.ImageBaseModel):
    def saving_path(self, name):
        return f"uploads/gallery_images/{self.item.id}/{name}"

    image = models.ImageField(
        "main image",
        upload_to=saving_path,
        help_text="Will be rendered at 300px",
    )

    item = models.ForeignKey(
        Item,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        verbose_name="gallery images",
        help_text="gallery images",
    )

    class Meta:
        verbose_name = "image"
        verbose_name_plural = "image gallery"
        default_related_name = "gallery_images"

lyceum/catalog/views.py
from django.contrib import messages
from django.http import HttpRequest
from django.http import HttpResponse
from django.shortcuts import redirect
from django.urls import reverse_lazy
import django.views.generic
from django.views.generic import DetailView
from django.views.generic.edit import FormMixin

import catalog.models
from catalog.models import Item
import rating.forms
import rating.models


class ItemListView(django.views.generic.ListView):
    template_name = "catalog/item_list.html"
    context_object_name = "items"
    queryset = Item.objects.catalog_list()


class NewItemListView(django.views.generic.ListView):
    template_name = "catalog/item_list.html"
    context_object_name = "items"
    queryset = Item.objects.new_item_list()


class FridayItemListView(django.views.generic.ListView):
    template_name = "catalog/item_list.html"
    context_object_name = "items"
    queryset = Item.objects.friday_item_list()


class UncheckedItemListView(django.views.generic.ListView):
    template_name = "catalog/item_list.html"
    context_object_name = "items"
    queryset = Item.objects.unchecked_item_list()


class ItemDetailView(FormMixin, DetailView):
    model = catalog.models.Item
    form_model = rating.models.Grade
    template_name = "catalog/item_detail.html"
    pk_url_kwarg = "id"
    context_object_name = "item"
    form_class = rating.forms.GradeForm

    def get_context_data(self, *args, **kwargs) -> dict:
        context = super().get_context_data(*args, **kwargs)

        sum_grades, number = 0, 0
        item_grades = rating.models.Grade.objects.get_item_grades(self.kwargs["id"])
        min_rating, max_rating = 6, 0
        for grade in item_grades:
            if grade.rating == "":
                continue
            sum_grades += int(grade.rating)
            number += 1
            if int(grade.rating) >= max_rating:
                user_max_rating = grade.user.username
                max_rating = int(grade.rating)
            if int(grade.rating) <= min_rating:
                user_min_rating = grade.user.username
                min_rating = int(grade.rating)
            if self.request.user.id == grade.user.id:
                context["user_grade"] = grade

        context["count_grades"] = number
        if number == 0:
            context["average_rate_value"] = 0
        else:
            context["average_rate_value"] = sum_grades / number
            context["user_max_rating"] = user_max_rating
            context["user_min_rating"] = user_min_rating
        return context

    def get_success_url(self, **kwargs):
        return reverse_lazy("catalog:item_detail", kwargs={"id": kwargs["id"]})

    def post(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        form = self.form_class(request.POST or None)
        if form.is_valid():
            if form.cleaned_data["rating"]:
                self.form_model.objects.update_or_create(
                    user_id=request.user.id,
                    item_id=self.kwargs["id"],
                    defaults=form.cleaned_data,
                )
                messages.success(request, "Product with a rating")
            else:
                self.form_model.objects.filter(
                    user_id=request.user.id, item_id=self.kwargs["id"]
                ).delete()
                messages.success(request, "Rating removed")
        return redirect(self.get_success_url(**self.kwargs))

lyceum/templates/catalog/index.html
{% extends 'layouts/layout.html' %}

{% block content %}
{% load static %}

<section class="blog-post-area section-margin">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="row">
                    <div class="col-md-6">
                        <div class="single-recent-blog-post card-view">
                            <div class="thumb">
                                <img class="card-img rounded-0" src="img/blog/thumb/thumb-card1.png" alt="">
                                <ul class="thumb-info">
                                    <li><a href="#"><i class="ti-user"></i>Admin</a></li>
                                    <li><a href="#"><i class="ti-themify-favicon"></i>2 Comments</a></li>
                                </ul>
                            </div>
                            <div class="details mt-20">
                                <a href="blog-single.html">
                                    <h3>Fast cars and rickety bridges as
                                        he grand tour returns</h3>
                                </a>
                                <p>Vel aliquam quis, nulla pede mi commodo no tristique nam hac luctus torquent velit
                                    felis lone commodo pellentesque</p>
                                <a class="button" href="#">Read More <i class="ti-arrow-right"></i></a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="single-recent-blog-post card-view">
                            <div class="thumb">
                                <img class="card-img rounded-0" src="img/blog/thumb/thumb-card2.png" alt="">
                                <ul class="thumb-info">
                                    <li><a href="#"><i class="ti-user"></i>Admin</a></li>
                                    <li><a href="#"><i class="ti-themify-favicon"></i>2 Comments</a></li>
                                </ul>
                            </div>
                            <div class="details mt-20">
                                <a href="blog-single.html">
                                    <h3>Harvey Weinstein's senual assault
                                        trial set for May</h3>
                                </a>
                                <p>Vel aliquam quis, nulla pede mi commodo no tristique nam hac luctus torquent velit
                                    felis lone commodo pellentesque</p>
                                <a class="button" href="#">Read More <i class="ti-arrow-right"></i></a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="single-recent-blog-post card-view">
                            <div class="thumb">
                                <img class="card-img rounded-0" src="img/blog/thumb/thumb-card3.png" alt="">
                                <ul class="thumb-info">
                                    <li><a href="#"><i class="ti-user"></i>Admin</a></li>
                                    <li><a href="#"><i class="ti-themify-favicon"></i>2 Comments</a></li>
                                </ul>
                            </div>
                            <div class="details mt-20">
                                <a href="blog-single.html">
                                    <h3>Fast cars and rickety bridges as
                                        he grand tour returns</h3>
                                </a>
                                <p>Vel aliquam quis, nulla pede mi commodo no tristique nam hac luctus torquent velit
                                    felis lone commodo pellentesque</p>
                                <a class="button" href="#">Read More <i class="ti-arrow-right"></i></a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="single-recent-blog-post card-view">
                            <div class="thumb">
                                <img class="card-img rounded-0" src="img/blog/thumb/thumb-card4.png" alt="">
                                <ul class="thumb-info">
                                    <li><a href="#"><i class="ti-user"></i>Admin</a></li>
                                    <li><a href="#"><i class="ti-themify-favicon"></i>2 Comments</a></li>
                                </ul>
                            </div>
                            <div class="details mt-20">
                                <a href="blog-single.html">
                                    <h3>Harvey Weinstein's senual assault
                                        trial set for May</h3>
                                </a>
                                <p>Vel aliquam quis, nulla pede mi commodo no tristique nam hac luctus torquent velit
                                    felis lone commodo pellentesque</p>
                                <a class="button" href="#">Read More <i class="ti-arrow-right"></i></a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="single-recent-blog-post card-view">
                            <div class="thumb">
                                <img class="card-img rounded-0" src="img/blog/thumb/thumb-card5.png" alt="">
                                <ul class="thumb-info">
                                    <li><a href="#"><i class="ti-user"></i>Admin</a></li>
                                    <li><a href="#"><i class="ti-themify-favicon"></i>2 Comments</a></li>
                                </ul>
                            </div>
                            <div class="details mt-20">
                                <a href="blog-single.html">
                                    <h3>Fast cars and rickety bridges as
                                        he grand tour returns</h3>
                                </a>
                                <p>Vel aliquam quis, nulla pede mi commodo no tristique nam hac luctus torquent velit
                                    felis lone commodo pellentesque</p>
                                <a class="button" href="#">Read More <i class="ti-arrow-right"></i></a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="single-recent-blog-post card-view">
                            <div class="thumb">
                                <img class="card-img rounded-0" src="img/blog/thumb/thumb-card6.png" alt="">
                                <ul class="thumb-info">
                                    <li><a href="#"><i class="ti-user"></i>Admin</a></li>
                                    <li><a href="#"><i class="ti-themify-favicon"></i>2 Comments</a></li>
                                </ul>
                            </div>
                            <div class="details mt-20">
                                <a href="blog-single.html">
                                    <h3>Harvey Weinstein's senual assault
                                        trial set for May</h3>
                                </a>
                                <p>Vel aliquam quis, nulla pede mi commodo no tristique nam hac luctus torquent velit
                                    felis lone commodo pellentesque</p>
                                <a class="button" href="#">Read More <i class="ti-arrow-right"></i></a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="single-recent-blog-post card-view">
                            <div class="thumb">
                                <img class="card-img rounded-0" src="img/blog/thumb/thumb-card7.png" alt="">
                                <ul class="thumb-info">
                                    <li><a href="#"><i class="ti-user"></i>Admin</a></li>
                                    <li><a href="#"><i class="ti-themify-favicon"></i>2 Comments</a></li>
                                </ul>
                            </div>
                            <div class="details mt-20">
                                <a href="blog-single.html">
                                    <h3>Fast cars and rickety bridges as
                                        he grand tour returns</h3>
                                </a>
                                <p>Vel aliquam quis, nulla pede mi commodo no tristique nam hac luctus torquent velit
                                    felis lone commodo pellentesque</p>
                                <a class="button" href="#">Read More <i class="ti-arrow-right"></i></a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="single-recent-blog-post card-view">
                            <div class="thumb">
                                <img class="card-img rounded-0" src="img/blog/thumb/thumb-card8.png" alt="">
                                <ul class="thumb-info">
                                    <li><a href="#"><i class="ti-user"></i>Admin</a></li>
                                    <li><a href="#"><i class="ti-themify-favicon"></i>2 Comments</a></li>
                                </ul>
                            </div>
                            <div class="details mt-20">
                                <a href="blog-single.html">
                                    <h3>Harvey Weinstein's senual assault
                                        trial set for May</h3>
                                </a>
                                <p>Vel aliquam quis, nulla pede mi commodo no tristique nam hac luctus torquent velit
                                    felis lone commodo pellentesque</p>
                                <a class="button" href="#">Read More <i class="ti-arrow-right"></i></a>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-12">
                        <nav class="blog-pagination justify-content-center d-flex">
                            <ul class="pagination">
                                <li class="page-item">
                                    <a href="#" class="page-link" aria-label="Previous">
                                <span aria-hidden="true">
                                    <i class="ti-angle-left"></i>
                                </span>
                                    </a>
                                </li>
                                <li class="page-item active"><a href="#" class="page-link">1</a></li>
                                <li class="page-item"><a href="#" class="page-link">2</a></li>
                                <li class="page-item">
                                    <a href="#" class="page-link" aria-label="Next">
                                <span aria-hidden="true">
                                    <i class="ti-angle-right"></i>
                                </span>
                                    </a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
            {% include 'include/sidebar.html' %}
        </div>
    </div>
</section>
{% endblock %}

lyceum/templates/catalog/item_detail.html
{% extends 'layouts/layout.html' %}
{% load static %}
{% load i18n %}

{% block title %}
<title>{% translate 'Fluffy' %} {{ item.name }}</title>
{% endblock %}

{% block content %}
<div class="blog-post-area section-margin">
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        <div class="main_blog_details"> <div class="image__wrapper"><img class="img-fluid card-img" src="{{ item.main_image.image.url }}" alt=""> <a class="btn-reply" href="{% url 'download:download_image' item.main_image.image.url %}">Скачать картинку</a> </div>
            <div class="card__name">
                <h4 class="detail__title">{{ item.name }}</h4>
            </div>
          <div class="user_details">
            <div class="float-left"> <a href="#">{% translate 'Get to know him better' %}</a> <a href="#">{% translate 'Pick up this pet' %}</a> </div>
            <div class="float-right mt-sm-0 mt-3">
            </div>
          </div>
          <div class="text">
            {{ item.text|safe }}
          </div>
          <h3 class="gallery__name">
            Gallery
          </h3>
          <div class="gallery">
            {% for card in item.gallery_images.all %}
              <div class="gallery__wrapper">
                <div class="gallery__items">
                  <h5 class="gallery__title">
                    title - {{ card.name }}
                  </h5>
                  <img class="card-img gallery__image" src="{{ card.image.url }}" alt="#" class="gallery__image">
                </div>
                <a class="btn-reply" href="{% url 'download:download_image' item.main_image.image.url %}">Скачать картинку</a>
              </div>
            {% endfor %}
          </div>
        </div>
          <div class="rating row col-12 mt-4">
            <div class="h4 d-inline col-6">
              <p class="mb-4 border-bottom">
              {% translate "Average user rating:" %}
              {{ average_rate_value }}<br>{{ average_rating_name }}<br>
              </p>
              <p class="mb-4 border-bottom">
              {% translate "Number of ratings:" %}
              {{ count_grades }}
              </p>
              <p class="mb-4 border-bottom">
              {% translate "The user who left the most positive rating:" %}
              {{ user_max_rating }}
              </p>
              <p class="mb-4 border-bottom">
              {% translate "The user who left the most negative rating:" %}
              {{ user_min_rating }}
              </p>
            </div>

            {% if user.is_authenticated %}
            <div class="d-inline col-6">
            <form method="post" class="block">
              {% csrf_token %}
                {% for message in messages %}
                  <div class="container xxl-8">
                    <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                      {{ message }}
                    </div>
                  </div>
                {% endfor %}
              <div>
                {% for field in form %}
                {% if not field.field.disabled  %}
                <div class="form-group">
                  <label class="font-weight-bold"
                         for="{{ field.id_for_label }}">
                    {{ field.label }}</label>
                  {{ field }}
                  {% if field.errors %}
                  <div class="text-danger">
                    {% translate 'Errors' %}
                    {{ field.errors|safe }}
                  </div>
                  {% endif %}

                  <div>{{ field.help_text }}</div>
                </div>
                {% endif %}
                {% endfor %}
              </div>

              <div class="col-12 text-center">
                <input type="submit" value="{% translate 'Save' %}"
                       class="btn btn-primary">
              </div>
            </form>
            </div>
            {% endif %}
          </div>

      </div>
      <!-- Start Blog Post Siddebar -->{% include 'include/sidebar.html' %}
      <!-- End Blog Post Siddebar -->
    </div>
  </div>
</div> {% endblock %}

lyceum/templates/catalog/item_list.html
{% extends 'layouts/layout.html' %}
{% load static %}
{% load i18n %}

{% block title %}
<title>{% translate 'Fluffies catalog'%}</title>
{% endblock %}

{% block content %}
<div class="blog-post-area section-margin">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="row">
          {% with request.resolver_match.view_name as view_name %}
            {% if view_name == 'catalog:item_list' %}
              {% regroup items by category.name  as category_list %}
                {% for category in category_list %}
                <h2 class="col-md-12 text-center">{{category.grouper}}</h2>
                {% for item in category.list %}
                <div class="col-md-4">
                  {% include 'include/item_card.html' %}
                </div>
                {% endfor %}
                {% empty %}
              <p>Видимо, тут товаров пока нету =(</p>
            {% endfor %}
            {% else %}
              {% for item in items %}
                <div class="col-md-4">
                  {% include 'include/item_card.html' %}
                </div>
              {% empty %}
                <p>Видимо, тут товаров пока нету =(</p>
              {% endfor %}
              {% endif %}
          {% endwith %}
        </div>
      </div>
    </div>
  </div>
</div> {% endblock %}